name: Deploy and Run LMS
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:

  deploy:
    name: Deploy LMS
    runs-on: ubuntu-latest
    steps:
    - name: copy file via ssh using key
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.QA_HOST }}
        username: ${{ secrets.QA_APP_USER }}
        key: ${{ secrets.QA_APP_SECRET }}
        source: "."
        target: "/apps/lms"
        rm: "true"
